version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_PORT=8000

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
